---
title: "BTRY 4110: final project, data cleaning"
author: "ik273"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 1}
library(stringr)
library(dplyr)
# READ IN DATA
movies_raw <- read.csv("movies_raw.csv", row.names = 1 )
movies <- movies_raw
```

## Clean Data


```{r 2}
# change class of each variable
  # change running time
running_times_matrix <- str_match(movies$Running.Time, "(\\d+) hr(?: (\\d+) min)?")[,c(2,3)]
running_times_matrix <- matrix(as.integer(running_times_matrix), ncol = 2, byrow = F)
running_times_matrix[,1] <- running_times_matrix[,1] * 60
movies$Running.Time <- rowSums(running_times_matrix, na.rm=T)

  # change all money variables
movies$Total.Gross <- as.numeric( gsub("[\\$,]", "", movies$Total.Gross) )
movies$Opening <- as.numeric( gsub("[\\$,]", "", movies$Opening) )
movies$Budget <- as.numeric( gsub("[\\$,]", "", movies$Budget) )
movies$Weekly <- as.numeric( gsub("[\\$,]", "", movies$Weekly) )
movies$To.Date <- as.numeric( gsub("[\\$,]", "", movies$To.Date) )

  # change Release Date
movies$Release.Date <- as.Date(movies$Release.Date)
movies$ReleaseDate_2 <- as.Date(movies$ReleaseDate_2, format = "%b %d, %Y")
movies$Release.Date <- coalesce(movies$Release.Date, movies$ReleaseDate_2)
movies$ReleaseDate_2 <- NULL

  # change Date variable
    # set the variable as the first day of the week that it represents
    # example: Jul 21-27 becomes Jul 21
movies$Date <- sub("-.*", "-2023", movies$Date)
movies$Date <- as.Date(movies$Date, format = "%b %d-%Y")

  # change remaining variables
movies$Tickets.Sold <- as.numeric( gsub("[,]", "", movies$Tickets.Sold) )
movies$Theaters <- as.numeric( gsub("[,]", "", movies$Theaters) )

```

```{r 3}
# fix variable names
colnames(movies) <- c("Overall_Rank", "Movie", "Running_Time", "Total_Gross", "Release_Date", "Distributor", "Opening_Gross", "MPAA", "Genre", "Tickets_Sold", "Budget", "WeekDate", "Weekly_Gross", "Theaters", "Gross_To_Date", "Week")


# add missing data
movies[1787, "Week"] <- 1
movies[1787, "Weekly_Gross"] <- 1290000
movies[1787, "Gross_To_Date"] <- 1290000
movies[1787, "MPAA"] <- "PG-13"


# Fill in missing Opening_Gross data
movies$Opening_Gross[c(1531:1538 )] <- 3006525
movies$Opening_Gross[c(1609:1611)] <- 973795
movies$Opening_Gross[1897] <- 1176085

# Fill in missing MPAA data 
movies$MPAA[which(is.na(movies$MPAA))] <- "Not Rated"
movies$MPAA[c(1365,1366)] <- "PG" #TV equivalent of PG 
movies$MPAA[c(1650,1651)] <- "R"
movies$MPAA[c(1790:1827)] <- "PG"

#Fill in missing Theaters data
movies$Theaters[1693:1698] <- 62
movies$Theaters[c(1715,1716)] <- c(1175, 925)

#Fill in missing Genre data
movies$Genre[1467:1475] <- "Adventure"
movies$Genre[1631:1641] <- "Comedy"
movies$Genre[1653:1660] <- "Comedy"
movies$Genre[1683:1689] <- "Action"
movies$Genre[1742:1749] <- "Drama"


# check for missing data
anyNA(movies$Running_Time)
anyNA(movies$Total_Gross)
anyNA(movies$Release_Date)
anyNA(movies$Distributor)
anyNA(movies$Opening_Gross)
anyNA(movies$MPAA)
anyNA(movies$Genre)
anyNA(movies$Tickets_Sold) # yes
anyNA(movies$Budget) # yes
anyNA(movies$WeekDate)
anyNA(movies$Weekly_Gross)
anyNA(movies$Theaters)
anyNA(movies$Gross_To_Date)
anyNA(movies$Week)

# remove any rows with unusual data
```

```{r}
# scratch code (delete later)
View(movies)

which(is.na(movies$Theaters))
which(is.na(movies$Tickets_Sold))
which(is.na(movies$Budget))
which(movies$Distributor=="-")
movies[616,]
```


