---
title: "KNN-MovieData-Code"
author: "az296"
date: "2024-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#K-Nearest Neighbors Algorithm On Movies DataSet (az296)

#

#First We Set Up the Merge for our red and white wine datasets

df_red <- read.csv("C:/Users/andre/Desktop/Cornell/Senior Fall/BTRY4740/Final Project/wine+quality/winequality-red.csv", sep = ";")
df_red["Wine_Type"] <- "red"
df_white <- read.csv("C:/Users/andre/Desktop/Cornell/Senior Fall/BTRY4740/Final Project/wine+quality/winequality-white.csv", sep = ";")
df_white["Wine_Type"] <- "white"
wine_full <- rbind(df_red,df_white)
df_white["Wine_Type"] <- toString(df_white["Wine_Type"])

#I will split the data into training and validation, and will calculate the prediction accuracy of KNN on the validation data

n <- length(wine_full$fixed.acidity)
unrand_index <- 1:n
rand_index <- sample(unrand_index)
breakpoint <- n %/% 2
training_index <- rand_index[1:breakpoint]
validation_index <- rand_index[(breakpoint+1):n]
training_data <- wine_full[training_index,]
validation_data <- wine_full[validation_index,]

#Now, we can proceed with fitting our KNN model on the training data
library(caret)
set.seed(1)
trainControl <- trainControl(method="repeatedcv",number=10,repeats=3)
fit.knn <- train(quality~., 
                 data = training_data, 
                 method="knn", 
                 preProcess=c("center","scale"),
                 trcontrol=trainControl)
print(fit.knn)

#Thus, according to our K-Fold Cross validation, we will proceed with the k=9 nearest neighbors
#model since it has the lowest Training RMSE
test_pred <- predict(fit.knn,newdata=validation_data)
test_pred <- round(test_pred)
validation_data["pred_quality"] <- test_pred
accuracy <- mean(validation_data$quality == validation_data$pred_quality)
statement_KNN <- paste0("The test accuracy of our KNN algorithm with K=9 is: ", round(accuracy,digits=3))
print(statement_KNN)

#K-Means Clustering on Movies Dataset 
library(dplyr)
load(r"[C:\Users\andre\Desktop\Cornell\Senior Spring\BTRY4100\Final_Project\simple_movies.RData]")
sm_tib<-as_tibble(simple_movies)
continous_numeric_cols <- col
for (i in 1:length(names(sm_tib))){
  if(class(sm_tib[names(sm_tib)[i]][[1]]) %in% c("integer","numeric")){
    
  }
}
```
