---
title: "Shiny App Interface"
author: "jrc447"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("shiny")
library("ggplot2")
library("bslib")
library("DT")


# Import movie data

load("movies.RData")
load("simple_movies.RData")
```


```{r}
# Plotting functions for use in Server Controls

plotDistributor = function(plotthis) {
  ## Plotting top 10 Movie Distributors
  
    # sort top Distributors
  temp <- tail(sort(table(movies$Distributor), decreasing=FALSE), n=10)
  temp <- data.frame(temp)
  names(temp) <- c("Distributor", "Movies_Released")
  
    # plot box plot
  ggplot(data=temp, aes(Distributor, Movies_Released)) + geom_col() + coord_flip()
}


plotBasic = function(plotthis){
  simple_movies
}


plotKMeans = function(plotthis){
  
  sm_tib<-as_tibble(simple_movies)
  continous_numeric_cols <- c(5,7,8)
  
  #Standardization of continous numeric data in our movies dataset 
  for (i in 1:length(names(sm_tib))){
    if(class(sm_tib[names(sm_tib)[i]][[1]]) %in% c("integer","numeric")){
      continous_numeric_cols<-c(continous_numeric_cols,i)
    }
  }
  sm_tib_k <- sm_tib[,continous_numeric_cols]
  sm_tib_k <- sm_tib_k[c(-8,-9)]
  for (i in 4:(length(sm_tib_k))){
    sm_tib_k[,i] <- (sm_tib_k[,i]-mean(sm_tib_k[,i][[1]]))/sd(sm_tib_k[,i][[1]])
  }

  
  clustering <- kmeans(sm_tib_k[,4:7], as.numeric(plotthis)) 
  sm_tib_k$cluster<-clustering$cluster
  
    #plot clusters
  factoextra::fviz_cluster(clustering, sm_tib_k[,4:7], geom="point")
}


```


```{r}
# Shiny App 


# Shiny App UI
ui <- page_navbar(
  title = "Top Grossing Movies of 2023",
  inverse = TRUE,
  
    # Interactive panels 
  navset_card_underline(
    nav_panel("Basic Movie Information", 
              tabPanel("", DTOutput("basic")
                       ),
              ),
    nav_panel("Top Distributors", plotOutput("dist")),
    nav_panel("K Means", 
              page_sidebar(
                sidebar = sidebar(
                  helpText(
                    "Using Genre as Categorical Variable"
                  ),
                  selectInput(
                    "var",
                    label = "Choose K",
                    choices = 
                      list(
                        "13",
                        "4",
                        "56"
                      )
                  )
                ),
                plotOutput("selected_var")
              )
              )
    ),
  
  nav_spacer(),
  
  nav_menu(
    title = "Links",
    align = "right",
      # Links to source data
    nav_item(tags$a("2023 Domestic Box Office", href = "https://www.boxofficemojo.com/year/2023/?ref_=bo_yl_table_2")),
    nav_item(tags$a("Supplemental Data", href = "https://www.the-numbers.com/market/2023/top-grossing-movies"))
  ),
  nav_menu(
    title = "Authors",
    align = "right",
    nav_item("James Chun"),
    nav_item("Ilona Khimey"), 
    nav_item("Andrew Zhang")
  ),
  fluid=TRUE
)


server <- function(input, output) {
  ## Shiny App Server Controls

  output$basic <- renderDT(
    plotBasic(input$thisvar)
  )

  output$dist <- renderPlot(
    plotDistributor(input$thisvar)
  )
  
  output$selected_var <- renderPlot({
    plotKMeans(input$var)
  })
}

shinyApp(ui, server)


```



```{r}
# Scratch Code


# Average Running Time
#mean(unique(movies$Running_Time))

```



```{r}
# plot with gross profits  vs budget
model <- lm(log(Total_Gross) ~ log(Budget), data=simple_movies)

ggplot() + 
  geom_point(data=simple_movies, aes(x= log(Budget), y=log(Total_Gross), col=Overall_Rank)) +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") + 
  geom_abline(slope = model$coefficients[2], intercept = model$coefficients[1], color = "deeppink") + 
  xlab("Log of Budgets (in dollars)") + 
  ylab("Log of Total Gross Profits (in dollars)") + 
  ggtitle("Gross Profits vs Budget") +
  geom_text(aes(x = 9.8, y = 20, label = "x=y"), col="red") + 
  scale_color_gradient(low = "blue", high = "yellow")

# Display: For every 1% increase in budget, profirs increase by 0.6%
model$coefficients[2]
```
```{r 2}
# plot with budget vs rank
model2 <- lm(Budget~Overall_Rank, data = simple_movies)

ggplot() + 
  geom_point(data=simple_movies, aes(x= Overall_Rank, y=Budget/1000000)) +
  geom_abline(slope = -model2$coefficients[2]/1000000, intercept = model2$coefficients[1]/1000000, color = "blue") + 
  xlab("Rank") + 
  ylab("Budget (in millions of dollars)") + ggtitle("Budget vs Rank") + 
  scale_x_reverse() 

#Display this: To decrease 1 unit in rank (lower rank is better), budget increases by approximately $745,000
-model2$coefficients[2]
```





